import Head from 'next/head'
import Header from '../components/header'
import Wraper from '../components/wraper'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import HeaderMobile from '../components/mobile/headerMobile'
import AboutMeMobile from '../components/mobile/aboutMeMobile'
import SkillsMobile from '../components/mobile/skillsMobile'
import ProjectsMobile from '../components/mobile/projectsMobile'
import ContactMobile from '../components/mobile/contactMobile'


export default function Home() {
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    if (window.innerWidth < 768) {
      setIsMobile(true)
    }
  }, [])

  //If user is in mobile, return something else
  if (isMobile) {
    return(
      <div>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swap" rel="stylesheet" />
        </Head>
        
        <HeaderMobile></HeaderMobile>
        <AboutMeMobile></AboutMeMobile>
        <SkillsMobile></SkillsMobile>
        <ProjectsMobile></ProjectsMobile>
        <ContactMobile></ContactMobile>
      </div>
    )
  }else{
    return (
      <div className={styles.home}>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swap" rel="stylesheet" />
        </Head>
  
        <Header></Header>
        <Wraper></Wraper>
        
      </div>
    )
  }

  
}
