import Head from 'next/head'
import Header from '../components/header'
import Wraper from '../components/wraper'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swap" rel="stylesheet" />
      </Head>

      <Header></Header>
      <Wraper></Wraper>
      
    </div>
  )
}
